services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    command: uvicorn backend.main:rag_voice_agent_api --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    command: streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    depends_on:
      - backend
